### ISSUE TITLE
Add file importer for Cachix plugin

### ISSUE THREAD

**Issue by jpcoenen** [1Password/shell-plugins#111]
### Platform or tool

Cachix

### Desired or expected behavior

The Cachix CLI can store auth tokens to a file: `~/.config/cachix/cachix.dhall`. The shell plugin should be able to import a token in this file.

See the original [PR](https://github.com/1Password/shell-plugins/pull/97) that implemented the plugin for more details.

### Current behavior

Only tokens in the `CACHIX_AUTH_TOKEN` environment variable are imported.

**Comment by abhishekd1996** [comment]
Is issue Resolved?

**Comment by dethancosta** [comment]
I've been looking into this to take a crack at it. I'm not very familiar with dhall files, but the only package I could find that looks appropriate is https://github.com/philandstuff/dhall-golang/v6. I understand from reading the [contributing guidelines](https://github.com/1Password/shell-plugins/blob/main/CONTRIBUTING.md) that adding third-party dependencies is undesirable, but I'm unaware of another solution, other than hard-coding a line-by-line read of the file, which seems brittle. I've written an implementation on a local branch that uses this package and is ready for a PR, if that's acceptable.  Otherwise, I'd welcome any suggestions/pointers to other possible solutions.
