### ISSUE TITLE
New plugin: Vercel CLI

### ISSUE THREAD

**Issue by bala-ceg** [1Password/shell-plugins#304]
### Platform or tool

Vercel

### Relevant links

https://vercel.com/docs/getting-started-with-vercel
https://vercel.com/docs/cli

### Goal or desired behavior

Authenticate & Connect to Vercel  CLI 

### Contribution

- [X] I'd be up for building the plugin myself.

**Comment by bala-ceg** [comment]
@AndyTitu @volodymyrZotov Please assign this issue to me

**Comment by arunsathiya** [comment]
Hey @bala-ceg, thank you for your interest in building a shell plugin for Vercel! There's already a Vercel shell plugin in the final stages of the review:

- https://github.com/1Password/shell-plugins/pull/273

We'd love to see shell plugins for other Developer Experience tools you use though!

**Comment by AndyTitu** [comment]
I will be re-opening this until the plugin for Vercel gets merged, since there is no other issue opened to track this change. 

@bala-ceg if you'd like, please do take a look at the already existing PR Arun mentioned to review additionally or to pick it up from the almost completed state. It seems the PR is approved and only blocked by some unsigned commits though, so only reviewing would make more sense.

**Comment by AndyTitu** [comment]
The Vercel  plugin has been merged https://github.com/1Password/shell-plugins/pull/273
