### ISSUE TITLE
`gh auth` integration and bad `GITHUB_TOKEN` value?

### ISSUE THREAD

**Issue by chriskrycho** [1Password/shell-plugins#364]
### Platform or tool

GitHub CLI

### Desired or expected behavior

`gh auth login` etc. should work normally!

### Current behavior

```
$ gh auth login
? What account do you want to log into? GitHub.com
The value of the GITHUB_TOKEN environment variable is being used for authentication.
To have GitHub CLI store credentials instead, first clear the value from the environment.
```

Notably, checking my shell for whether `GITHUB_TOKEN` is set or not *prior* to running the command indicates the answer is "no":

```
$ if set -q GITHUB_TOKEN; echo variable defined; else; gh auth login; end
? What account do you want to log into? GitHub.com
The value of the GITHUB_TOKEN environment variable is being used for authentication.
To have GitHub CLI store credentials instead, first clear the value from the environment.
```

I have confirmed that the behavior is specific to when using the `op` + `gh` integration; if I disable the integration with `op` (by commenting out the relevant line in my `config.fish` and starting a new shell), `gh` falls back to its normal web-based flow as I would expect.

See also https://github.com/cli/cli/issues/7800.

### op CLI version

2.19.0

**Comment by arunsathiya** [comment]
Hi @chriskrycho, thanks for reaching out! Great that you have identified that your current auth is using 1Password shell plugin for GitHub. The idea of the shell plugin is to get the token once, store it in your 1Password vault and use it for all authentication going forward. That's how command `gh auth status` was working for you. Behind the scenes, 1Password shell plugin for GitHub provisions the secret as the `GITHUB_TOKEN` environment variable, which is why the GitHub CLI was reporting that the authentication is happening with that token. 

And as you figured, you can remove the shell plugin alias from your shell file for all authentication for `gh` to go through the regular flows that GitHub CLI offers. 

But I am curious to learn more about your goal -- is there a specific reason why you are running `gh auth login` instead of continuing to use the token that you have on the 1Password vault?

**Comment by chriskrycho** [comment]
Ah, fair question; that's helpful. Background: I'm actually *trying* to use the token via the 1Password vault (and have been doing so successfully for the last several days), and stumbled on this while trying to debug another issue, namely that GitHub was rejecting pushes to a given repo for the `workflow` permission when using a personal access token. (It's possible there's an issue on the GH side, but I assumed the issue was likely caching or some such in my local config.) I refreshed the token on GH itself, updated it in 1Password, and and attempted to do a `gh auth refresh` to make sure everything was plumbed through the system correctly… at which point I hit this issue: any of `refresh`, `login`, `logout` all failed with this failure mode. (Those may have been useless and irrelevant.)

At this point I'm in the hellscape of "the 1Password part seems to be fine now but `git push` itself isn't respecting the `credential`s set in `.gitconfig` and is therefore not going via `gh` and thus `op`?!?". Ugh. I'll close this for now and reopen it if I end up with something actionable/reproducible.

**Comment by arunsathiya** [comment]
>I refreshed the token on GH itself, updated it in 1Password, and and attempted to do a gh auth refresh to make sure everything was plumbed through the system correctly… 

At this point, a `gh auth refresh` is not necessary. All `gh` commands will automatically use the new token (the one that you manually generated on GitHub website and updated the 1Password item) from the 1Password vault.

>at which point I hit this issue: any of refresh, login, logout all failed with this failure mode. (Those may have been useless and irrelevant.)

`auth login`, `auth logout` and `auth status` are all irrelevant commands once one starts using 1Password shell plugin for GitHub. 

I was going to say that we not require 1Password auth for these commands by defining them here:

https://github.com/1Password/shell-plugins/blob/0b46a42d5295cf0fa1bedbf6b6356f7f7568778e/plugins/github/gh.go#L16-L18

But it's starting to feel that things can remain as is because 1Password auth takes place first for these commands and then, GH CLI correctly explains the error that `GITHUB_TOKEN` is set (by 1Password:

```
➜  ~ gh auth login
? Locate your GitHub Personal Access Token: GitHub PAT (Personal)

? What account do you want to log into? GitHub.com
The value of the GITHUB_TOKEN environment variable is being used for authentication.
To have GitHub CLI store credentials instead, first clear the value from the environment.


➜  ~ gh auth refresh
The value of the GITHUB_TOKEN environment variable is being used for authentication.
To refresh credentials stored in GitHub CLI, first clear the value from the environment.


➜  ~ gh auth logout
The value of the GITHUB_TOKEN environment variable is being used for authentication.
To erase credentials stored in GitHub CLI, first clear the value from the environment.
```

Hope that helps explain what shell plugin does.

**Comment by arunsathiya** [comment]
>At this point I'm in the hellscape of "the 1Password part seems to be fine now but git push itself isn't respecting the credentials set in .gitconfig and is therefore not going via gh and thus op?!?". Ugh. I'll close this for now and reopen it if I end up with something actionable/reproducible.

This is a different issue though and I see that we somebody else already reported it in Feb 2022:

- https://github.com/1Password/shell-plugins/issues/174

I am not too familiar with git credential helpers but [I read about it](https://git-scm.com/docs/gitcredentials), and based on my learnings, `git` (not `gh`) actions requiring GitHub auth should use the underlying auth that `gh` supports. For those with the 1Password shell plugin, it'd be `GITHUB_TOKEN` and for others, it'd be Apple Keychain, because that's where GH CLI stores the token these days.

In my case, `gh auth setup-git` adds this to my `.gitconfig`:

```
[credential "https://github.com"]
	helper = 
	helper = !/opt/homebrew/bin/gh auth git-credential
[credential "https://gist.github.com"]
	helper = 
	helper = !/opt/homebrew/bin/gh auth git-credential
```

So my understanding is that `git push` command actually uses GH CLI-facilitated, Keychain-stored credentials instead of the token from 1Password vault.

Something similar should be happening for you too. If something else is happening, could you elaborate a bit on that?

**Comment by arunsathiya** [comment]
Assuming you don't have GitHub token stored on the Apple Keychain and have it only on the 1Password vault, you can replace `!/opt/homebrew/bin/gh` with `op plugin run -- gh` on `.gitconfig`. That seems to do the trick for me. 

When I ran `git push`, the 1Password fingerprint prompt popped up, which indicates that the credential being used for the push is the one stored on the 1Password vault.

**Comment by chriskrycho** [comment]
In case anyone else happens to end up here—

The problem I ended up with (and which the combination of tools made quite hard to diagnose) was that the config `gh` sets in `.gitconfig` to use `gh` as the credential manager when you run `gh auth setup-git` is not, out of the box, able to see the shell alias that `op` sets up when you do `op plugin init gh`. The shell that `git` uses to run all of its commands ends up seeing the actual `gh` program (and indeed, `gh auth setup-git` explicitly sets it to the full path to `gh`), so it will *never* run through the `gh` which is the result of `alias gh="op plugin run -- gh"`.

I worked around this by replacing the `credential` entries in `.gitconfig` with an explicit call to `op` instead:

```diff
[credential "https://github.com"]
    helper =
-   helper = !/opt/homebrew/bin/gh auth git-credential
+   helper = !/usr/local/bin/op plugin run -- gh auth git-credential
[credential "https://gist.github.com"]
    helper =
-   helper = !/opt/homebrew/bin/gh auth git-credential
+   helper = !/usr/local/bin/op plugin run -- gh auth git-credential
```

Now everything works as I wanted it to in the first place. (1Password folks, if there's a better way to do this, I am of course all ears!)

**Comment by chriskrycho** [comment]
@arunsathiya ha! I hadn't refreshed the page since earlier in the day, so I only saw your comment *after* mine was posted – good to know that I landed in the same place. 💙

**Comment by ascarter** [comment]
> Assuming you don't have GitHub token stored on the Apple Keychain and have it only on the 1Password vault, you can replace `!/opt/homebrew/bin/gh` with `op plugin run -- gh` on `.gitconfig`. That seems to do the trick for me.

`gh` has a command `gh auth setup-git` which puts in the credential helper entries. It would be cool if when aliased via `op` that the call for `gh auth setup-git` would produce the `op run` version instead. Since you are wrapping `gh`, can you just intercept and answer this directly without letting it go to `gh`? Also could intercept `login`, `logout`, and `refresh` and give a message that 1Password is managing the GitHub auth.
